#!/usr/bin/env bash

# regex to validate in commit msg
commit_regex='([A-Z]+-[0-9]+|merge|FIX|UPDATE)'
error_msg="Aborting commit. Your commit message is missing either a JIRA Issue or 'Merge' or 'FIX' or 'UPDATE'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi